language: c

# For doc-building dependencies.
cache: pip

addons:
  apt:
    packages:
      - tk-dev
      - liblzma-dev
      - python-pip

os:
  - linux
  - osx

dist: trusty
sudo: false
group: beta

compiler:
  - clang
  - gcc

env:
  - TESTING=cpython

matrix:
  include:
    - os: linux
      language: python
      python: 3.5
      env:
        - TESTING=docs
      before_script:
        - cd Doc
        - make venv PYTHON=python3
      script:
        - make html SPHINXBUILD="./venv/bin/python3 -m sphinx" SPHINXOPTS="-nW -q -b linkcheck"

# Travis provides only 2 cores.
before_script:
  - ./configure --with-pydebug
  - make -j4

script:
  # `-r -w` implicitly provided as arguments to `test`.
  - make test TESTOPTS="-uall -j4"

notifications:
  email: false
